-- Migration: Create account_activation table
-- Description: Create account_activation table for 4-digit activation codes with 60-second expiration
-- Date: 2025-11-04 13:19:49
-- depends: 20251103_160000_create_account_table

-- This migration creates the `account_activation` table for storing temporary
-- activation codes sent to users during registration workflow.
--
-- Design Decisions:
--   - account_id as PRIMARY KEY (enforces one code per account business rule)
--   - Foreign key to account.id with CASCADE delete (cleanup when account deleted)
--   - code stored as VARCHAR(4) (4-digit numeric code from ActivationCode VO)
--   - TIMESTAMPTZ for created_at/expires_at (UTC timestamps from Python)
--   - No surrogate id needed (account_id is natural primary key)
--
-- Business Rules Enforced:
--   - One active code per account (PK constraint)
--   - Code expires 60 seconds after creation (expires_at logic in application)
--   - Activation deleted when account deleted (CASCADE)
--
-- Performance Considerations:
--   - Optional index on expires_at for future cleanup jobs
--   - account_id PK provides fast lookups (O(log n))
--
-- Security:
--   - Codes are ephemeral (60s lifetime)
--   - No need for separate delete operation in MVP
--   - UPSERT pattern prevents code accumulation

CREATE TABLE IF NOT EXISTS account_activation (
    -- Primary Key: account_id (enforces one code per account)
    -- Also serves as foreign key to account table
    account_id UUID PRIMARY KEY,

    -- Activation Code: 4-digit numeric code (generated by ActivationCode VO)
    code VARCHAR(4) NOT NULL,

    -- Creation Timestamp: When activation was created (UTC)
    created_at TIMESTAMPTZ NOT NULL,

    -- Expiration Timestamp: When activation expires (created_at + 60 seconds)
    expires_at TIMESTAMPTZ NOT NULL,

    -- Foreign Key: Link to account table with CASCADE delete
    CONSTRAINT fk_account_activation_account
        FOREIGN KEY (account_id)
        REFERENCES account(id)
        ON DELETE CASCADE
);

-- Optional Index: Accelerate expiration-based cleanup queries (future optimization)
-- Not critical for MVP but useful for batch cleanup jobs
CREATE INDEX IF NOT EXISTS idx_account_activation_expires_at
    ON account_activation(expires_at);

-- Comments for schema documentation
COMMENT ON TABLE account_activation IS 'Temporary activation codes for account verification (60-second lifetime)';
COMMENT ON COLUMN account_activation.account_id IS 'Primary key and foreign key to account table (one code per account)';
COMMENT ON COLUMN account_activation.code IS '4-digit numeric activation code sent to user email';
COMMENT ON COLUMN account_activation.created_at IS 'Activation creation timestamp (UTC, immutable)';
COMMENT ON COLUMN account_activation.expires_at IS 'Activation expiration timestamp (created_at + 60 seconds)';